

class VerifyOTP {
  String otp;
  String status;


  VerifyOTP({this.otp});

  fromJson(Map<String, dynamic> json) {
    otp = json['otp'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['otp'] = this.otp;
    data['status'] = this.status;
    return data;
  }
}


class SignUpResponse {
  String status;
  String msg;
  String user_id;

  SignUpResponse({this.status, this.msg, this.user_id});

  fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    status = json['status'];
    user_id = json['user_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this.msg;
    data['status'] = this.status;
    data['user_id'] = this.user_id;
    return data;
  }
}

class LoginResponse {
  String status;
  String msg;
  String user_id;

  LoginResponse({this.status, this.msg, this.user_id});

  fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    status = json['status'];
    user_id = json['user_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this.msg;
    data['status'] = this.status;
    data['user_id'] = this.user_id;
    return data;
  }
}

class UserStatusResponse {
  String status;
  String msg;
  String user_id;
  bool kingaPofile;
  bool personal_profile_status;
  bool bike_profile_status;
  bool next_of_kin_status;
  bool colleague_status;

  UserStatusResponse({this.status, this.msg, this.user_id, this.kingaPofile, this.personal_profile_status,
    this.bike_profile_status, this.next_of_kin_status, this.colleague_status});

  fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    status = json['status'];
    user_id = json['user_id'];
    kingaPofile = json['kinga_profile_status'];
    personal_profile_status = json['personal_profile_status'];
    bike_profile_status = json['bike_profile_status'];
    next_of_kin_status = json['next_of_kin_status'];
    colleague_status = json['colleague_status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this.msg;
    data['status'] = this.status;
    data['user_id'] = this.user_id;
    data['kinga_profile_status'] = this.kingaPofile;
    data['personal_profile_status'] = this.personal_profile_status;
    data['bike_profile_status'] = this.bike_profile_status;
    data['next_of_kin_status'] = this.next_of_kin_status;
    data['colleague_status'] = this.colleague_status;

    return data;
  }
}


class Autogenerated {
  String status;
  String msg;
  List<Colleague> colleague;
  List<Colleague> nextOfKin;

  Autogenerated({this.status, this.msg, this.colleague, this.nextOfKin});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    msg = json['msg'];
    if (json['colleague'] != null) {
      colleague = new List<Colleague>();
      json['colleague'].forEach((v) {
        colleague.add(new Colleague.fromJson(v));
      });
    }
    if (json['Next_of_kin'] != null) {
      nextOfKin = new List<Colleague>();
      json['Next_of_kin'].forEach((v) {
        nextOfKin.add(new Colleague.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['msg'] = this.msg;
    if (this.colleague != null) {
      data['colleague'] = this.colleague.map((v) => v.toJson()).toList();
    }
    if (this.nextOfKin != null) {
      data['Next_of_kin'] = this.nextOfKin.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Colleague {
  String userId;
  String name;
  String contactNo;

  Colleague({this.userId, this.name, this.contactNo});

  Colleague.fromJson(Map<String, dynamic> json) {
    userId = json['user_id'];
    name = json['name'];
    contactNo = json['Contact_no'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user_id'] = this.userId;
    data['name'] = this.name;
    data['Contact_no'] = this.contactNo;
    return data;
  }
}


class EmailResponse {
  String status;
  String msg;

  EmailResponse({this.status, this.msg});

  fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this.msg;
    data['status'] = this.status;
    return data;
  }
}
